package main

type FlatProfileRequest struct {
	RollNo               string  `json:"roll_no"`
	Name                 string  `json:"name"`
	DateOfBirth          string  `json:"date_of_birth"`
	MobileNumber         string  `json:"mobile_number"`
	AltMobileNumber      string  `json:"alt_mobile_number"`
	PersonalEmail        string  `json:"personal_email"`
	LinkedInUrl          string  `json:"linkedin_url"`
	FatherName           string  `json:"father_name"`
	FatherMobile         string  `json:"father_mobile"`
	FatherOccupation     string  `json:"father_occupation"`
	FatherCompanyDetails string  `json:"father_company_details"`
	FatherEmail          string  `json:"father_email"`
	MotherName           string  `json:"mother_name"`
	MotherMobile         string  `json:"mother_mobile"`
	MotherOccupation     string  `json:"mother_occupation"`
	MotherEmail          string  `json:"mother_email"`
	ResidenceType        string  `json:"residence_type"`
	Address              string  `json:"address"`
	City                 string  `json:"city"`
	Pincode              *string `json:"pincode"` // Can be null
	AdhaarNo             string  `json:"adhaar_no"`
	Photo                string  `json:"photo"`
	CompanyAim           string  `json:"company_aim"`
	TargetPackage        string  `json:"target_package"`
	TenthPercentage      string  `json:"tenth_percentage"`
	TwelthPercentage     string  `json:"twelth_percentage"`
	CgpaSem1             *string `json:"cgpa_sem1"`
	CgpaSem2             *string `json:"cgpa_sem2"`
	CgpaSem3             *string `json:"cgpa_sem3"`
	CgpaSem4             *string `json:"cgpa_sem4"`
	CgpaOverall          string  `json:"cgpa_overall"`
	CurrentBacklogs      string  `json:"current_backlogs"`
	HasBacklogHistory    string  `json:"has_backlog_history"`
	Certifications       string  `json:"certifications"`
	Awards               string  `json:"awards"`
	Workshops            string  `json:"workshops"`
	Internships          string  `json:"internships"`
	// Skills
	SkillC         string `json:"skill_c"`
	SkillCpp       string `json:"skill_cpp"`
	SkillJava      string `json:"skill_java"`
	SkillPython    string `json:"skill_python"`
	SkillNodeJs    string `json:"skill_node_js"`
	SkillSql       string `json:"skill_sql"`
	SkillNoSql     string `json:"skill_no_sql"`
	SkillWebDev    string `json:"skill_web_dev"`
	SkillPhp       string `json:"skill_php"`
	SkillFlutter   string `json:"skill_flutter"`
	SkillAptitude  string `json:"skill_aptitude"`
	SkillReasoning string `json:"skill_reasoning"`
	// Concepts
	ConceptDataStructures string `json:"concept_data_structures"`
	ConceptDbms           string `json:"concept_dbms"`
	ConceptOops           string `json:"concept_oops"`
	ConceptProblemSolving string `json:"concept_problem_solving"`
	ConceptNetworks       string `json:"concept_networks"`
	ConceptOs             string `json:"concept_os"`
	ConceptAlgos          string `json:"concept_algos"`
	// Tools
	ToolGit         string `json:"tool_git"`
	ToolLinux       string `json:"tool_linux"`
	ToolCloud       string `json:"tool_cloud"`
	ToolHackerRank  string `json:"tool_hacker_rank"`
	ToolHackerEarth string `json:"tool_hacker_earth"`

	CommunicationSkills string `json:"communication_skills"`
	HackathonsAttended  string `json:"hackathons_attended,omitempty"`
	Extracurriculars    string `json:"extracurriculars,omitempty"`
	ClubParticipation   string `json:"club_participation,omitempty"`
	FuturePath          string `json:"future_path,omitempty"`
	Strength            string `json:"strength,omitempty"`
	Weakness            string `json:"weakness,omitempty"`
	Remarks             string `json:"remarks,omitempty"`
}

type FlatProfileResponse struct {
	RollNo                string  `json:"roll_no"`
	Name                  string  `json:"name"`
	OfficialEmail         string  `json:"official_email"`
	DateOfBirth           string  `json:"date_of_birth"`
	MobileNumber          string  `json:"mobile_number"`
	AltMobileNumber       string  `json:"alt_mobile_number"`
	PersonalEmail         string  `json:"personal_email"`
	LinkedInUrl           string  `json:"linkedin_url"`
	FatherName            string  `json:"father_name"`
	FatherMobile          string  `json:"father_mobile"`
	FatherOccupation      string  `json:"father_occupation"`
	FatherCompanyDetails  string  `json:"father_company_details"`
	FatherEmail           string  `json:"father_email"`
	MotherName            string  `json:"mother_name"`
	MotherMobile          string  `json:"mother_mobile"`
	MotherOccupation      string  `json:"mother_occupation"`
	MotherEmail           string  `json:"mother_email"`
	ResidenceType         string  `json:"residence_type"`
	Address               string  `json:"address"`
	City                  string  `json:"city"`
	Pincode               string  `json:"pincode"`
	AdhaarNo              string  `json:"adhaar_no"`
	CompanyAim            string  `json:"company_aim"`
	TargetPackage         string  `json:"target_package"`
	TenthPercentage       string  `json:"tenth_percentage"`
	TwelthPercentage      string  `json:"twelth_percentage"`
	CgpaSem1              *string `json:"cgpa_sem1"`
	CgpaSem2              *string `json:"cgpa_sem2"`
	CgpaSem3              *string `json:"cgpa_sem3"`
	CgpaSem4              *string `json:"cgpa_sem4"`
	CgpaOverall           string  `json:"cgpa_overall"`
	CurrentBacklogs       string  `json:"current_backlogs"`
	HasBacklogHistory     string  `json:"has_backlog_history"`
	Certifications        string  `json:"certifications"`
	Awards                string  `json:"awards"`
	Workshops             string  `json:"workshops"`
	Internships           string  `json:"internships"`
	SkillC                string  `json:"skill_c"`
	SkillCpp              string  `json:"skill_cpp"`
	SkillJava             string  `json:"skill_java"`
	SkillPython           string  `json:"skill_python"`
	SkillNodeJs           string  `json:"skill_node_js"`
	SkillSql              string  `json:"skill_sql"`
	SkillNoSql            string  `json:"skill_no_sql"`
	SkillWebDev           string  `json:"skill_web_dev"`
	SkillPhp              string  `json:"skill_php"`
	SkillFlutter          string  `json:"skill_flutter"`
	SkillAptitude         string  `json:"skill_aptitude"`
	SkillReasoning        string  `json:"skill_reasoning"`
	ConceptDataStructures string  `json:"concept_data_structures"`
	ConceptDbms           string  `json:"concept_dbms"`
	ConceptOops           string  `json:"concept_oops"`
	ConceptProblemSolving string  `json:"concept_problem_solving"`
	ConceptNetworks       string  `json:"concept_networks"`
	ConceptOs             string  `json:"concept_os"`
	ConceptAlgos          string  `json:"concept_algos"`
	ToolGit               string  `json:"tool_git"`
	ToolLinux             string  `json:"tool_linux"`
	ToolCloud             string  `json:"tool_cloud"`
	ToolCompCoding        string  `json:"tool_comp_coding"`
	ToolHackerRank        string  `json:"tool_hacker_rank"`
	ToolHackerEarth       string  `json:"tool_hacker_earth"`
	CommunicationSkills   string  `json:"communication_skills"`
	HackathonsAttended    string  `json:"hackathons_attended"`
	Extracurriculars      string  `json:"extracurriculars"`
	ClubParticipation     string  `json:"club_participation"`
	FuturePath            string  `json:"future_path"`
	Strength              string  `json:"strength"`
	Weakness              string  `json:"weakness"`
	Remarks               string  `json:"remarks"`
}
